// src/styles/GameStyles.js

export const modernStyles = {
  container: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    height: '100vh',
    position: 'relative',
    overflow: 'hidden',
  },
  sidebar: {
    width: '25%',
    minWidth: '300px',
    height: '100%',
    backgroundColor: '#f8f9fa',
    boxShadow: '0 0 10px rgba(0,0,0,0.1)',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 10,
  },
  mapArea: {
    flex: 1,
    height: '100%',
    position: 'relative',
    zIndex: 5,
  },
  mapControls: {
    position: 'absolute',
    bottom: '20px',
    right: '20px',
    display: 'flex',
    flexDirection: 'row',
    gap: '10px',
    zIndex: 20,
  },
  mapButton: {
    width: '45px',
    height: '45px',
    borderRadius: '50%',
    backgroundColor: 'white',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    transition: 'transform 0.2s ease, background-color 0.2s ease',
  },
  activeMapButton: {
    width: '45px',
    height: '45px',
    borderRadius: '50%',
    backgroundColor: '#34d399',
    color: 'white',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    transition: 'transform 0.2s ease, background-color 0.2s ease',
  },
  scorecardButton: {
    width: '45px',
    height: '45px',
    borderRadius: '50%',
    backgroundColor: 'white',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.2)',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    position: 'absolute',
    bottom: '20px',
    right: '75px',
    zIndex: 20,
    transition: 'transform 0.2s ease, background-color 0.2s ease',
    '&:hover': {
      transform: 'scale(1.05)',
      backgroundColor: '#f8f8f8'
    }
  },
  scoreboard: {
    marginBottom: '20px',
  },
  scoreHeader: {
    marginBottom: '15px',
  },
  shotInfo: {
    marginBottom: '15px',
  },
  clubSelector: {
    marginBottom: '15px',
  },
  messageContainer: {
    flex: 1,
    overflowY: 'auto',
    marginBottom: '20px',
    padding: '10px',
    backgroundColor: '#fff',
    borderRadius: '8px',
    boxShadow: 'inset 0 0 5px rgba(0,0,0,0.1)',
  },
  announcer: {
    padding: '8px',
    marginBottom: '8px',
    backgroundColor: '#e6f7ff',
    borderRadius: '5px',
  },
  user: {
    padding: '8px',
    marginBottom: '8px',
    backgroundColor: '#f0f0f0',
    borderRadius: '5px',
    textAlign: 'right',
  },
  shotButton: {
    padding: '12px',
    backgroundColor: '#34d399',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  ballMarker: {
    width: '12px',
    height: '12px',
    background: 'white',
    border: '2px solid black',
    borderRadius: '50%',
  },
  pinMarker: {
    width: '10px',
    height: '20px',
    background: 'red',
    borderRadius: '10px 10px 0 0',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 100,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  puttingModal: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '10px',
    textAlign: 'center',
    boxShadow: '0 0 20px rgba(0,0,0,0.2)',
    maxWidth: '400px',
  },
  primaryButton: {
    padding: '10px 20px',
    backgroundColor: '#34d399',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '15px',
  }
};
  